#ifndef TEXT_EDITOR_PAGE_MAP_H
#define TEXT_EDITOR_PAGE_MAP_H

typedef enum TextEditorTextFlag
{
    TEXT_EDITOR_TEXT_FLAG_TEXT = 0,
    TEXT_EDITOR_TEXT_FLAG_TAB,
    TEXT_EDITOR_TEXT_FLAG_NEW_LINE,
    TEXT_EDITOR_TEXT_FLAG_REMOVE_NEXT_CHAR,
    TEXT_EDITOR_TEXT_FLAG_REMOVE_PREV_CHAR,
    TEXT_EDITOR_TEXT_FLAG_REMOVE_PAGE,
    TEXT_EDITOR_TEXT_FLAG_TRUCATE_LINE,
} TextEditorTextFlag;

typedef enum TextEditorCursorFlag
{
    TEXT_EDITOR_CURSOR_FLAG_MOVE    = 0 << 0,
    TEXT_EDITOR_CURSOR_FLAG_SELECT  = 1 << 0,

    TEXT_EDITOR_CURSOR_FLAG_CHAR    = 0 << 1,
    TEXT_EDITOR_CURSOR_FLAG_LINE    = 1 << 1,
    TEXT_EDITOR_CURSOR_FLAG_PAGE    = 2 << 1,

    TEXT_EDITOR_CURSOR_FLAG_UP      = 0 << 3,
    TEXT_EDITOR_CURSOR_FLAG_DOWN    = 1 << 3,
    TEXT_EDITOR_CURSOR_FLAG_LEFT    = 2 << 3,
    TEXT_EDITOR_CURSOR_FLAG_RIGHT   = 3 << 3,

    TEXT_EDITOR_CURSOR_FLAG_BEGIN   = 0 << 3,
    TEXT_EDITOR_CURSOR_FLAG_END     = 1 << 3,

    TEXT_EDITOR_CURSOR_FLAG_PREV    = 0 << 3,
    TEXT_EDITOR_CURSOR_FLAG_NEXT    = 1 << 3,
} TextEditorCursorFlag;

#endif // TEXT_EDITOR_PAGE_MAP_H
